import {
  CircleDot,
  Circle,
  Target,
  Waves,
  Bike,
  Dumbbell,
  Guitar,
  Piano,
  Mic,
  Headphones,
  Music,
  Palette,
  Camera,
  Pencil,
  Box,
  Clapperboard,
  Gamepad2,
  Dices,
  Crown,
  Trophy,
  Telescope,
  Atom,
  FlaskConical,
  Dna,
  Ruler,
  Laptop,
  Bot,
  Brain,
  Smartphone,
  Mountain,
  Sprout,
  PawPrint,
  Globe,
  Plane,
  Languages,
  Earth,
  ChefHat,
  Croissant,
  Coffee,
  BookOpen,
  Rocket,
  Scroll,
  MessageCircle,
  Calculator,
  Sigma,
  type LucideProps,
} from 'lucide-react';

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  'circle-dot': CircleDot,
  'circle': Circle,
  'target': Target,
  'waves': Waves,
  'bike': Bike,
  'dumbbell': Dumbbell,
  'guitar': Guitar,
  'piano': Piano,
  'mic': Mic,
  'headphones': Headphones,
  'music': Music,
  'palette': Palette,
  'camera': Camera,
  'pencil': Pencil,
  'box': Box,
  'clapperboard': Clapperboard,
  'gamepad-2': Gamepad2,
  'dices': Dices,
  'crown': Crown,
  'trophy': Trophy,
  'telescope': Telescope,
  'atom': Atom,
  'flask-conical': FlaskConical,
  'dna': Dna,
  'ruler': Ruler,
  'laptop': Laptop,
  'bot': Bot,
  'brain': Brain,
  'smartphone': Smartphone,
  'mountain': Mountain,
  'sprout': Sprout,
  'paw-print': PawPrint,
  'globe': Globe,
  'plane': Plane,
  'languages': Languages,
  'earth': Earth,
  'chef-hat': ChefHat,
  'croissant': Croissant,
  'coffee': Coffee,
  'book-open': BookOpen,
  'rocket': Rocket,
  'scroll': Scroll,
  'message-circle': MessageCircle,
  'calculator': Calculator,
  'sigma': Sigma,
};

interface IconProps extends LucideProps {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    return null;
  }

  return <IconComponent {...props} />;
}
